language: cpp
compiler: gcc
dist: trusty
addons:
  apt:
    sources:
    - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - libboost-all-dev
    - libopenblas-dev
    - libdlib-dev
script:
- export CC=gcc-7
- export CXX=g++-7
- cmake .
- cmake --build .
- cmake --build . --target package

